### ISSUE TITLE
Default CLI args in a config file?

### ISSUE THREAD

**Issue by j6k4m8** [PyriteAI/pypk#4]
Default` ~/.config/pypk.json` but user-specified with `--config path/to/config.json`, it would be nice to set default values (overrideable with CLI args):

```shell
pypk --config ~/alternative-config/pypk.json <project_root>
```

`cat ~/.config/pypk.json`
```json
{
    "author_name": "Jordan Matelsky",
    "author_email": "Eat my shorts",
    "python_version": "3.9"
}
```

**Comment by mlw214** [comment]
Added in #5.
